# Generated by Django 4.0.5 on 2022-06-10 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("notes", "0001_initial"),
        ("notes", "0002_rename_latitude_location_latitude"),
        ("notes", "0003_alter_location_latitude_alter_location_longitude"),
        ("notes", "0004_category_remove_task_location_locationgroup_and_more"),
    ]

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("longitude", models.DecimalField(decimal_places=10, max_digits=13, verbose_name="Longitude")),
                ("latitude", models.DecimalField(decimal_places=10, max_digits=13, verbose_name="Latitude")),
                ("name", models.CharField(max_length=63, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="LocationGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63, verbose_name="Name")),
                ("locations", models.ManyToManyField(to="notes.location")),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=63, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("due_date", models.DateTimeField(blank=True, null=True, verbose_name="Due date/time")),
                ("assigned_group", models.ManyToManyField(to="auth.group")),
                (
                    "creator",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="notes.category")),
                (
                    "location_group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="notes.locationgroup"),
                ),
            ],
        ),
    ]
