# Generated by Django 4.0.5 on 2022-06-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="Latitude",
            new_name="latitude",
        ),
    ]
