# Generated by Django 4.0.5 on 2022-06-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("notes", "0003_category_range_task_range"),
        ("notes", "0004_remove_location_latitude_remove_location_longitude_and_more"),
        ("notes", "0005_remove_category_range_remove_location_location_and_more"),
        ("notes", "0006_category_range_task_range"),
    ]

    dependencies = [
        ("notes", "0002_alter_task_category_alter_task_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="range",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Range"),
        ),
        migrations.AddField(
            model_name="task",
            name="range",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Range"),
        ),
    ]
