# Generated by Django 4.0.5 on 2022-06-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_task_category_alter_task_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="range",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Range"),
        ),
        migrations.AddField(
            model_name="task",
            name="range",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Range"),
        ),
    ]
