# Generated by Django 4.0.5 on 2022-06-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_simplify_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=18, max_digits=28, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=18, max_digits=28, verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="location",
            name="radius_meters",
            field=models.DecimalField(decimal_places=18, max_digits=28, verbose_name="Radius Meters"),
        ),
    ]
