# Generated by Django 4.0.5 on 2022-06-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63, verbose_name="Name")),
            ],
        ),
        migrations.RemoveField(
            model_name="task",
            name="location",
        ),
        migrations.CreateModel(
            name="LocationGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=63, verbose_name="Name")),
                ("locations", models.ManyToManyField(to="notes.location")),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="notes.category"),
        ),
        migrations.AddField(
            model_name="task",
            name="location_group",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="notes.locationgroup"),
        ),
    ]
