# Generated by Django 4.0.5 on 2022-06-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_remove_location_latitude_remove_location_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="range",
        ),
        migrations.RemoveField(
            model_name="location",
            name="location",
        ),
        migrations.RemoveField(
            model_name="task",
            name="range",
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=10, default=1, max_digits=13, verbose_name="Latitude"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=10, default=1, max_digits=13, verbose_name="Longitude"),
            preserve_default=False,
        ),
    ]
